version: "3.7"

volumes:
  db_data:
  logs:
    driver: local

services:
  php:
    build: .
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
      MYSQL_HOST: db
      MYSQL_DATABASE: phinxui
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: rootpassword
      ENVIRONMENT: development
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
      - logs:/var/www/logs
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: phinxui
      MYSQL_USER: phinx_user
      MYSQL_PASSWORD: phinx_password
